/* Generated By:JavaCC: Do not edit this line. HypertextConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HypertextConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SENTENCE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"ADD\"",
    "\"IMAGE\"",
    "\"WITH\"",
    "\"SOURCE\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
    "<SENTENCE>",
  };

}
